In [2]:
list1 = [1, 2, 3, 4, 5]

In [1]:
import numpy as np

In [3]:
list1 = [1, 2, 3, 4, 5]
np.array(list1)

array([1, 2, 3, 4, 5])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.linspace(0, 11, 5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [16]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.15760864, 0.0638769 , 0.38444444, 0.21261816, 0.94901704])

In [20]:
np.random.rand(5, 5)

array([[0.0408173 , 0.89264499, 0.22754986, 0.2748813 , 0.85411862],
       [0.05197077, 0.35115934, 0.39557669, 0.46091042, 0.15214033],
       [0.57899214, 0.7134755 , 0.72809134, 0.32793109, 0.94824328],
       [0.38953824, 0.61136022, 0.08143082, 0.37095423, 0.65182449],
       [0.56936718, 0.27242025, 0.63540098, 0.09300904, 0.9426772 ]])

In [21]:
np.random.randn(9)

array([ 0.33553529,  0.49609513,  1.24550757,  0.92876794,  0.68635911,
       -0.13760506,  1.5415913 ,  0.89743875,  1.04783075])

In [22]:
np.random.randint(1, 100, 10)

array([53, 25, 19, 98, 84, 74, 48, 89, 47, 35])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0, 50, 10)

In [26]:
ranarr

array([19, 27, 33, 10, 36, 17, 39, 41,  5,  2])

In [7]:
arr = np.arange(25)
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

41

In [46]:
ranarr.min()

2

In [32]:
np.arange

<function numpy.arange>

In [44]:
ranarr

array([19, 27, 33, 10, 36, 17, 39, 41,  5,  2])

In [47]:
ranarr.argmax()

7

In [48]:
ranarr.argmin()

9